# fly.toml file generated for mysql-database on 2022-09-23T03:40:35Z

app = "mysql-database"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  MYSQL_DATABASE = "wp"
  MYSQL_ROOT_PASSWORD = "my-secret-pw"

[build]
  image = "mysql:8"

[experimental]
  cmd = [
      "--performance_schema=off",
      "--key_buffer_size=16M",
      "--tmp_table_size=1M",
      "--innodb_buffer_pool_size=1M",
      "--innodb_log_buffer_size=1M",
      "--max_connections=25",
      "--sort_buffer_size=512K",
      "--read_buffer_size=256K",
      "--read_rnd_buffer_size=512K",
      "--join_buffer_size=128K",
      "--thread_stack=196K",
      "--bind-address=::",
      "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--default-authentication-plugin", "mysql_native_password", "--datadir", "/data/mysql"]

[mounts]
  destination = "/data"
  source = "mysqldata"
